###
# Create answer
POST http://localhost:3000/answers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtAZ21haWwuY29tIiwic3ViIjo0LCJyb2xlcyI6WyJpbnZlc3RvciJdLCJpYXQiOjE3MTk5MTIwMzcsImV4cCI6MTcxOTk5ODQzN30.gAgIicY4MYXc9n1yy4pxYWkFyl24c4SrdQuIRI-55mc

{
    "text": "Seed/Start Up/Idea",
    "weight": 7,
    "questionId": 6,
    "recommendation": "Nairobi is the capital city of Kenya444"
}

###
# Get answer

GET http://localhost:3000/answers/2
Authorization: Bearer ..p47b04Rqv3OisSmfFjveei8PNWheYG_RsT9VTFNTb4U

###
# Get answers

GET http://localhost:3000/answers
Authorization: Bearer ..cbXz5KINj2vqIbMQf9e46mk5Y1l7mOnAJ2FWsPVPc-M

###
# Get answers paginated

GET http://localhost:3000/answers?page=1&limit=2
Authorization: Bearer ..p47b04Rqv3OisSmfFjveei8PNWheYG_RsT9VTFNTb4U

###
# Update answer

PUT http://localhost:3000/answers/2
Content-Type: application/json
Authorization: Bearer ..Jk9eEUCVmCuDbBJxp4Cj2diI1yeCWQHnydJ67_jru4k

{
    "recommendation": "Nairobi is the capital city of Kenya"
}

###
# Delete answer

DELETE http://localhost:3000/answers/1
Authorization: Bearer ..b7ALjsOASf4xdOd_xH2r8KPqoK0hpZqAQQP6ouDMTtg