### Landing 

GET http://localhost:3000

#####
### Landing 

GET http://localhost:3000/home

#####
# Sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "cthiaine@gmail.com",
    "password": "password"
}

#####
# Sign up prod
POST https://capitalconnect-0060e0fb0eb4.herokuapp.com/auth/signup
Content-Type: application/json

{
    "username": "mushakwe@gmail.com",
    "password": "pass123"
}

#####
# Login
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "k@gmail.com",
    "password": "password"
}

#####
# Sign up with name
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "Absalom",
    "password": "pass123",
    "firstName": "Mkuu"
}

###
# Login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
   "username": "vic@gmail.com",
    "password": "pass123"
}

###
# Login wrong creds || user

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "victor3@yahoo.com",
    "password": "pass112"
}

#####
# Sign up prod
POST https://capitalconnect-0060e0fb0eb4.herokuapp.com/auth/login
Content-Type: application/json

{
   "username": "vic@gmail.com",
    "password": "pass12"
}

###
# Resend verification email

POST http://localhost:3000/auth/resend-verification-email
Content-Type: application/json

{
    "email": "vic@gmail.com"
}

###
# Resend verification email

POST http://api.capitalconnect.africa/auth/resend-verification-email
Content-Type: application/json

{
    "email": "tech@capitalconnect.africa"
}
