### Landing 

GET http://localhost:3000

#####
### Landing 

GET http://localhost:3000/home

#####
# Sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "t@gmail.com",
    "password": "password"
}

#####
# Sign up
POST https://capitalconnect-0060e0fb0eb4.herokuapp.com/auth/signup
Content-Type: application/json

{
    "username": "vic@gmail.com",
    "password": "pass123"
}

#####
# Sign up with name
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "Absalom",
    "password": "pass123",
    "firstName": "Mkuu"
}

###
# Login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "chris@gmail.com",
    "password": "password"
}

###
# Login wrong creds || user

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "victor3@yahoo.com",
    "password": "pass1123"
}
