###
#Create booking

POST http://localhost:3000/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "calendlyEventId": "82348",
    "bookingProcessorId": "pesapal"
}

###
# Get booking

GET http://localhost:3000/bookings/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9


###
# Get bookings

GET http://localhost:3000/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get bookings paginated

GET http://localhost:3000/bookings?page=8&limit=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Update booking

PUT http://localhost:3000/bookings/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "calendlyEventId": "76098"
}

###
# Delete booking

DELETE http://localhost:3000/bookings/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9