###
# Create Company

POST http://localhost:3000/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "name": "Capital Connect",
    "country": "Kenya",
    "businessSector": "Venture Capital",
    "businessSubsector": "Capital Raising",
    "productsAndServices": "Fintech",
    "registrationStructure": "B2B",
    "yearsOfOperation": "0 - 1 years",
    "growthStage": "funded",
    "numberOfEmployees": "1-10 employees",
    "fullTimeBusiness": true
}
###
# Create Company prod

POST https://capitalconnect-0060e0fb0eb4.herokuapp.com/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "name": "Capital Connect",
    "country": "Kenya",
    "businessSector": "Venture Capital",
    "businessSubsector": "Capital Raising",
    "productsAndServices": "Fintech",
    "registrationStructure": "B2B",
    "yearsOfOperation": "0 - 1 years",
    "growthStage": "funded",
    "numberOfEmployees": "1-10 employees",
    "fullTimeBusiness": true
}

####
# Fetch Number of employees.
GET http://localhost:3000/company/list/no-of-employees

####
# Fetch Years of operation.
GET http://localhost:3000/company/list/years-of-operation

####
# Fetch companies

GET http://localhost:3000/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

####
# Fetch companies paginated

GET http://localhost:3000/company?page=4&limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

####
# Fetch company by id

GET http://localhost:3000/company/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9


####
# Fetch company by user id

GET http://localhost:3000/company/owner/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

####
# Fetch company by user id

GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/company/owner/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9


####
#Update company by id


PATCH http://localhost:3000/company/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "name": "Bazuu Enterprise 255",
    "country": "Tanzania",
    "businessSector": "Sector 1 updated",
    "businessSubsector": "Updated Sub Sector 1",
    "productsAndServices": "FMCG",
    "registrationStructure": "Partnership",
    "yearsOfOperation": "0 - 1 years",
    "growthStage": "Start-up - post revenues",
    "numberOfEmployees": "11-50 employees",
    "fullTimeBusiness": true
}

####
# Update company by id


PATCH http://localhost:3000/company/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "name": "Bazuu Enterprise 255",
    "country": "Tanzania",
    "businessSector": "Ecommerce",
    "productsAndServices": "FMCG",
    "registrationStructure": "B2C",
    "yearsOfOperation": " 0 - 1 years",
    "growthStage": "2",
    "numberOfEmployees": "495",
    "fullTimeBusiness": true
}

####
# Delete company byid
DELETE http://localhost:3000/company/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9


####
# Fetch investor matched businesses by id

GET http://localhost:3000/company/invesetor-matches/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9



####
# Fetch business matched investors by id

GET http://localhost:3000/company/business-matches/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

