### Create a new ContactPerson
POST http://localhost:3000/contact-persons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "firstName": "Jane",
  "lastName": "Doe",
  "designation": "Senior Manager",
  "emailAddress": "jane.doe@example.com",
  "phoneNumber": "+254771114712",
  "primaryContact": true,
  "investorProfileId": 1
}

###

### Get all ContactPersons
GET http://localhost:3000/contact-persons
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get investor profiles paginated
GET http://localhost:3000/investor-profiles?page=5&limit=50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###

### Get a specific ContactPerson
GET http://localhost:3000/contact-persons/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###

### Update a ContactPerson
PATCH http://localhost:3000/contact-persons/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "designation": "Senior Manager"
}

###

### Delete a ContactPerson
DELETE http://localhost:3000/contact-persons/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
