###
# Create Funding vehicle
POST http://localhost:3000/funding-vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "title": "Top",
    "description": "The highest level"
}

###
# Create Funding vehicle prod
POST http://api.capitalconnect.africa/funding-vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "title": "",
    "description": "The highest level"
}

###
# Get Funding vehicle
GET http://localhost:3000/funding-vehicles/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get Funding vehicle prod
GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/funding-vehicles/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get Funding vehicles
GET http://localhost:3000/funding-vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get Funding vehicles prod
GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/funding-vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get Funding Vehicles paginated
GET http://localhost:3000/funding-vehicles?page=4&limit=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9


###
# Update Funding vehicle
PUT http://localhost:3000/funding-vehicles/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "title": "Funding vehicle 1 updated",
    "description": "Funding vehicle 1 description updated"
}

###
# Update Funding vehicle prod
PUT http://api.capitalconnect.africa/funding-vehicles/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "title": "Funding vehicle 1 updated",
    "description": "Funding vehicle 1 description updated"
}

###
# Delete Funding vehicle
DELETE http://localhost:3000/funding-vehicles/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Delete Funding vehicle prod
DELETE http://api.capitalconnect.africa/funding-vehicles/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
