### Match companies based on investor profile criteria
GET http://localhost:3000/matchmaking/companies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Match companies based on investor profile criteria
GET http://localhost:3000/matchmaking/investor-profiles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9