###
# Send Otp

POST http://localhost:3000/otp
Content-Type: application/json

{
   "phoneNo": 0452234560
}

###
# Verify otp

POST http://localhost:3000/otp/verify
Content-Type: application/json

{
   "PhoneNo": 0452234560,
    "otp": 123851
}