###
# Create payment
POST http://localhost:3000/payments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "currency": "Ksh",
    "amount": 1000.00,
    "description": "payment test",
    "status": "payed",
    "orderTrackingId": "new",
    "bookingId": 5,
    "userId": 4
}

###
# Create payment prod
POST http://api.capitalconnect.africa/payments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "currency": "",
    "amount": 0,
    "description": "",
    "status": "",
    "OrderTrackingId": 0
}

###
# Get payment
GET http://localhost:3000/payments/b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get payment prod
GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/payments/129
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get payments
GET http://localhost:3000/payments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get payments prod
GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/payments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get payments paginated
GET http://localhost:3000/payments?page=3&limit=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get payments paginated prod
GET http://api.capitalconnect.africa/payments?page=1&limit=4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Update payment
PUT http://localhost:3000/payments/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "currency": "",
    "amount": 0,
    "description": "",
    "status": "",
    "OrderTrackingId": 0
}

###
# Update payment prod
PUT http://api.capitalconnect.africa/payments/129
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "currency": "",
    "amount": 0,
    "description": "",
    "status": "",
    "OrderTrackingId": 0
}

###
# Delete payment
DELETE http://localhost:3000/payments/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Check payment status
GET http://localhost:3000/payments/status?orderTrackingId=da31e1d4-87ac-4bf2-96f8-dcfc7150d847
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Check payment status prod
GET http://api.capitalconnect.africa/payments/status?orderTrackingId=55d9a645-6658-434b-8a74-dcf66fc61862
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

