###
# PesaPal API Authentication
POST https://pay.pesapal.com/v3/api/Auth/RequestToken
Content-Type: application/json

{
    "consumer_key": "l+25h9gMEidUxTgN/dgfdgsafhgads/Uq34",
    "consumer_secret": "3w+hhB/acsbncasbncban="
}

###
#

POST https://pay.pesapal.com/v3/api/PostPesapalDirectOrderV4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "amount": "100",
    "description": "Payment for goods",
    "type": "MERCHANT",
    "reference": "123456",
    "first_name": "John",
    "last_name": "Doe",
    "email": ""
    }

###
# PesaPal Callback URL local

POST http://localhost:3000/payments/callback
Content-Type: application/json

{
    "pesapal_merchant_reference": "123456",
    "pesapal_transaction_tracking_id": "QWERTY123456"
}

###
# PesaPal Callback URL

POST http://api.capitalconnect.africa/payments/callback
Content-Type: application/json

{
    "pesapal_merchant_reference": "123456",
    "pesapal_transaction_tracking_id": "QWERTY123456"
}

###
# Register IPN

POST https://pay.pesapal.com/v3/api/URLSetup/RegisterIPN
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "url": "http://api.capitalconnect.africa/payments/callback",
    "ipn_notification_type": "POST"
}

###
# Get IPN List

GET https://pay.pesapal.com/v3/api/URLSetup/GetIpnList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Submit order request

POST https://pay.pesapal.com/v3/api/Transactions/SubmitOrderRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "id": "3344ZZ",
    "currency": "KES",
    "amount": 10.00,
    "description": "This is a test payment",
    "callback_url": "https://app.capitalconnect.africa/payments/success",
    "redirect_mode": "",
    "notification_id": "65c77d95-af39-440d-88f5-dd0114174e1c",
    "branch": "Capital Connect Africa App",
    "billing_address": {
        "email_address": "mushakwe@gmail.com",
        "phone_number": "0771114712",
        "country_code": "KE",
        "first_name": "Victor",
        "middle_name": "Karanja",
        "last_name": "Nyambura",
        "line_1": "Pesapal Limited",
        "line_2": "",
        "city": "",
        "state": "",
        "postal_code": "",
        "zip_code": ""
    }
}  

###
# Get transaction status

GET https://pay.pesapal.com/v3/api/Transactions/GetTransactionStatus?orderTrackingId=8b409fc7-c24a-4e21-ab3c-dd01e92be2b6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3VzZXJkYXRhIjoiZTk5NjJhNGUtYzkwZS00ZGY4LWJkYTUtZGQwMWE5ZTQyYmQ0IiwidWlkIjoibCsyNWg5Z01FaWRVeFRnTi9MUzlUVEtUemZlL1VxMzQiLCJuYmYiOjE3MjA3ODE1NTcsImV4cCI6MTcyMDc4MTg1NywiaWF0IjoxNzIwNzgxNTU3LCJpc3MiOiJodHRwOi8vcGF5LnBlc2FwYWwuY29tLyIsImF1ZCI6Imh0dHA6Ly9wYXkucGVzYXBhbC5jb20vIn0.JzqeDBhwE0Pw3cCG_Ypoxu2jVkyMpQQ_WeRYq6NyPyo
