###
# Create question
POST http://localhost:3000/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "text": "What is the capital of Kenya 2?",
    "subSectionId": 3,
    "type": "SINGLE_CHOICE",
    "order": 10,
    "tooltip": "This is a tooltip"
}

# MULTIPLE_CHOICE, SINGLE_CHOICE, TRUE_FALSE, SHORT_ANSWER
###
# Get question

GET http://localhost:3000/questions/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get questions

GET http://localhost:3000/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpyZGFuZGlhYmVsdGFAZ21haWwuY29tIiwic3ViIjo2LCJyb2xlcyI6WyJ1c2VyIl0sImlhdCI6MTcyMDY5OTE2NiwiZXhwIjoxNzIwNzg1NTY2fQ.OF4tdJVdp1T-8SkNInRoumatR5GfHEUnDNN9LJjRon8

###
# Get questions paginated

GET http://localhost:3000/questions?page=1&limit=50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
###
# Get questions paginated

GET http://localhost:3000/questions/sub-section/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Update question

PUT http://localhost:3000/questions/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "text": "Updated question 1",
    "type": "MULTIPLE_CHOICE",
    "order": 9,
    "tooltip": "This is a tooltip Upgrade: 1"
}

###
# Delete question

DELETE http://localhost:3000/questions/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9