### Create Special criteria
POST http://localhost:3000/special-criteria
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
{
    "title": "",
    "description": ""
}

### Get Special criteria by Id
GET http://localhost:3000/special-criteria/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get all Special criteria
GET http://localhost:3000/special-criteria
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Update Special criteria
PUT http://localhost:3000/special-criteria
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
{
    "title": "",
    "description": ""
}

### Delete Special criteria by Id
DELETE http://localhost:3000/special-criteria/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9