### Create a single submission
POST http://localhost:3000/submissions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtAZ21haWwuY29tIiwic3ViIjo0LCJyb2xlcyI6WyJpbnZlc3RvciJdLCJpYXQiOjE3MTk5MTIwMzcsImV4cCI6MTcxOTk5ODQzN30.gAgIicY4MYXc9n1yy4pxYWkFyl24c4SrdQuIRI-55mc

{
  "userId": 4,
  "questionId": 6,
  "answerId": 9
}

### Create multiple submissions
POST http://localhost:3000/submissions/bulk
Content-Type: application/json
Authorization: Bearer ..yxUZhR3V4ZIkKHo4nQVXOA-Z2PmAUuASJNXMPqmEplQ

{
  "submissions": [
    {
      "userId": 6,
      "questionId": 4,
      "answerId": 1
    },
    {
      "userId": 6,
      "questionId": 3,
      "answerId": 3
    }
  ]
}

### Fetch submissions by user
GET http://localhost:3000/submissions/user/1
Authorization: Bearer ..3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo

### Calculate score for user
GET http://localhost:3000/submissions/user/6/score
Authorization: Bearer ..yxUZhR3V4ZIkKHo4nQVXOA-Z2PmAUuASJNXMPqmEplQ

### Calculate score for user per section 6 = userId 1 = sectionId
GET http://localhost:3000/submissions/user/6/score/1
Authorization: Bearer ..yxUZhR3V4ZIkKHo4nQVXOA-Z2PmAUuASJNXMPqmEplQ
