### Create a single submission
POST http://localhost:3000/submissions
Content-Type: application/json
Authorization: Bearer ..3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo

{
  "userId": 6,
  "questionId": 11,
  "answerId": 17
}

### Create multiple submissions
POST http://localhost:3000/submissions/bulk
Content-Type: application/json
Authorization: Bearer ..3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo

{
  "submissions": [
    {
      "userId": 6,
      "questionId": 1,
      "answerId": 1
    },
    {
      "userId": 6,
      "questionId": 3,
      "answerId": 4
    },
    {
      "userId": 6,
      "questionId": 4,
      "answerId": 3
    },
    {
      "userId": 6,
      "questionId": 2,
      "answerId": 2
    }
  ]
}

### Fetch submissions by user
GET http://localhost:3000/submissions/user/6
Authorization: Bearer ..3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo

### Fetch submissions by user prod
GET http://api.capitalconnect.africa/submissions/user/4
Authorization: Bearer ..3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo

### Fetch submissions by user per section
GET http://localhost:3000/submissions/user/6/section/1
Authorization: Bearer ..3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo

### Fetch submissions by user per section prod
GET http://api.capitalconnect.africa/submissions/user/6/section/1
Authorization: Bearer ..3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo

### Calculate score for user
GET http://localhost:3000/submissions/user/6/score
Authorization: Bearer ..3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo

### Calculate score for user per section 6 = userId 1 = sectionId
GET http://localhost:3000/submissions/user/6/score/1
Authorization: Bearer ..3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo


### Calculate score for user for all sections
GET http://localhost:3000/submissions/user/6/scores
Authorization: Bearer ..3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo
