###
# Create section
POST http://localhost:3000/subsections
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpY0BnbWFpbC5jb20iLCJzdWIiOjEsInJvbGVzIjpbImFkbWluIiwidXNlciJdLCJpYXQiOjE3MTc3NjI1MjAsImV4cCI6MTcxNzg0ODkyMH0.cw849nBSjuZxLkcR3XTBsAIGnxykPo9OqjKs_mDQ-nM

{
    "name": "Section 100",
    "sectionId": 1,
    "description": "Section 100 description"
}

###
# Get sub section

GET http://localhost:3000/subsections/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpY0BnbWFpbC5jb20iLCJzdWIiOjEsInJvbGVzIjpbImFkbWluIiwidXNlciJdLCJpYXQiOjE3MTc3NjI1MjAsImV4cCI6MTcxNzg0ODkyMH0.cw849nBSjuZxLkcR3XTBsAIGnxykPo9OqjKs_mDQ-nM

###
# Get sub sections

GET http://localhost:3000/subsections
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdWxAeWFob28uY29tIiwic3ViIjoyOCwicm9sZXMiOlsidXNlciJdLCJpYXQiOjE3MTc3NDQ2NTcsImV4cCI6MTcxNzgzMTA1N30.3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo

###
# Get sub sections paginated

GET http://localhost:3000/subsections?page=1&count=30
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdWxAeWFob28uY29tIiwic3ViIjoyOCwicm9sZXMiOlsidXNlciJdLCJpYXQiOjE3MTc3NDQ2NTcsImV4cCI6MTcxNzgzMTA1N30.3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo

###
# Update section

PUT http://localhost:3000/subsections/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpY0BnbWFpbC5jb20iLCJzdWIiOjEsImlhdCI6MTcxNzE0Mzk2NywiZXhwIjoxNzE3MjMwMzY3fQ.CHZ9vGGtrwOYt9v1hGnK6hOjNNSxFSwh8gihUaplyQE

{
    "name": "Updated Sub Section 1",
    "description": "Updated Sub Section 1 description"
}

###
# Delete section

DELETE http://localhost:3000/subsections/37
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpY0BnbWFpbC5jb20iLCJzdWIiOjEsImlhdCI6MTcxNzE0Mzk2NywiZXhwIjoxNzE3MjMwMzY3fQ.CHZ9vGGtrwOYt9v1hGnK6hOjNNSxFSwh8gihUaplyQE

###
# Get section questions

GET http://localhost:3000/subsections/2/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdWxAeWFob28uY29tIiwic3ViIjoyOCwicm9sZXMiOlsidXNlciJdLCJpYXQiOjE3MTc3NDQ2NTcsImV4cCI6MTcxNzgzMTA1N30.3fJsm0xhzodY2CTo-bPTmgPkxyVEeab4NACx2JtX1xo