###
# Profile

GET http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpY3RvcjNAeWFob28uY29tIiwic3ViIjoyMSwicm9sZXMiOlsidXNlciJdLCJpYXQiOjE3MTc0OTkxNjgsImV4cCI6MTcxNzU4NTU2OH0.qdhBhn2z6IXAyzQot8YrhWy5xHNhzhRgno-QFt8VFEo

###
# Users

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpY0BnbWFpbC5jb20iLCJzdWIiOjEsInJvbGVzIjpbInVzZXIiLCIgYWRtaW4iXSwiaWF0IjoxNzE3NDk1NjI5LCJleHAiOjE3MTc1ODIwMjl9.E4XM_eVTCpJ6r9LH0lqidc1mas36xhjR2GFGqgbLk6Q

###
# Update user

PUT http://localhost:3000/users/16
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpY0BnbWFpbC5jb20iLCJzdWIiOjEsInJvbGVzIjpbInVzZXIiLCJhZG1pbiJdLCJpYXQiOjE3MTc0OTcyNDYsImV4cCI6MTcxNzU4MzY0Nn0.DS0mR6DdQiNvQV5vHrlUDk05Lfu4wiT-VODgOGmLeP4

{
    "password": "pass1234",
    "firstName": "Victor",
    "lastName": "Karanja",
    "roles": "user,admin"
}

###
# Update user by admin

PUT http://localhost:3000/users/21/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpY0BnbWFpbC5jb20iLCJzdWIiOjEsInJvbGVzIjpbInVzZXIiLCJhZG1pbiJdLCJpYXQiOjE3MTc0OTcyNDYsImV4cCI6MTcxNzU4MzY0Nn0.DS0mR6DdQiNvQV5vHrlUDk05Lfu4wiT-VODgOGmLeP4

{
    "roles": "investor,user"
}